//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marketwatch.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Marketwatch.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Authentification ähnelt.
        /// </summary>
        internal static string AUTH {
            get {
                return ResourceManager.GetString("AUTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die :  ähnelt.
        /// </summary>
        internal static string AUTH_EMAIL_POST {
            get {
                return ResourceManager.GetString("AUTH_EMAIL_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the auth code sent to the email at  ähnelt.
        /// </summary>
        internal static string AUTH_EMAIL_PRE {
            get {
                return ResourceManager.GetString("AUTH_EMAIL_PRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter your 2 factor auth code from your authenticator app: ähnelt.
        /// </summary>
        internal static string AUTH_MOBILE {
            get {
                return ResourceManager.GetString("AUTH_MOBILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Purchase ähnelt.
        /// </summary>
        internal static string BUY_ITEM {
            get {
                return ResourceManager.GetString("BUY_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Market link invalid! ähnelt.
        /// </summary>
        internal static string FIX_LINK_MSGBOX_CAPTION {
            get {
                return ResourceManager.GetString("FIX_LINK_MSGBOX_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter a valid steam market link. 
        ///
        ///Example:  ähnelt.
        /// </summary>
        internal static string FIX_LINK_MSGBOX_TEXT {
            get {
                return ResourceManager.GetString("FIX_LINK_MSGBOX_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inspect ähnelt.
        /// </summary>
        internal static string INSPECT_ITEM {
            get {
                return ResourceManager.GetString("INSPECT_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login failed! ähnelt.
        /// </summary>
        internal static string LOGIN_FAILED {
            get {
                return ResourceManager.GetString("LOGIN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login required. ähnelt.
        /// </summary>
        internal static string LOGIN_MSGBOX_CAPTION {
            get {
                return ResourceManager.GetString("LOGIN_MSGBOX_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please login to your steam account first. If you already are logged in just wait a few seconds.  ähnelt.
        /// </summary>
        internal static string LOGIN_MSGBOX_TEXT {
            get {
                return ResourceManager.GetString("LOGIN_MSGBOX_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to logon to Steam:  ähnelt.
        /// </summary>
        internal static string LOGIN_UNABLE {
            get {
                return ResourceManager.GetString("LOGIN_UNABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;. ähnelt.
        /// </summary>
        internal static string PURCHASE_SUCCESS_POST {
            get {
                return ResourceManager.GetString("PURCHASE_SUCCESS_POST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Successfully purchased &quot; ähnelt.
        /// </summary>
        internal static string PURCHASE_SUCCESS_PRE {
            get {
                return ResourceManager.GetString("PURCHASE_SUCCESS_PRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sold! ähnelt.
        /// </summary>
        internal static string SOLD {
            get {
                return ResourceManager.GetString("SOLD", resourceCulture);
            }
        }
    }
}
